//go:build linux

package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	"tbound/supervisor/internal/delta"
	"tbound/supervisor/internal/sandbox"
	"tbound/supervisor/internal/sessionlaunch"
	"tbound/supervisor/internal/sessionrepo"
)

// The explicit `serve --pi --dev-fixture` route needs a real, durable Bash
// lease so the pinned Pi worker can drive the full read -> edit -> bash -> read
// workflow offline. The route prefers the reviewed `internal/sandbox` runner
// (the measured `dev-wsl-non-claim-bearing` cell). When that sandbox cannot be
// established on a development host (no Landlock ABI, missing namespaces), it
// falls back to the bounded, explicitly non-contained runner below rather than
// faking containment. Neither runner is a production containment profile.
const (
	// devFixtureCommandProfile labels the bounded fallback runner in durable
	// evidence. It states plainly that the runner establishes no containment.
	devFixtureCommandProfile = "dev-fixture-bounded-non-claim-bearing:direct-bash"

	// devFixtureCommandTimeout bounds one development command's wall clock.
	devFixtureCommandTimeout = 30 * time.Second

	// devFixtureCommandOutputMax caps each captured stream. It is no larger than
	// the session repository's own per-stream bound.
	devFixtureCommandOutputMax = 1 << 20

	// devFixtureCommandScopeGrace bounds how long the runner waits for the
	// command's process group to become empty after the direct child exits.
	devFixtureCommandScopeGrace = 2 * time.Second

	// devFixtureCommandLeaseLimit bounds retained view/lease registrations.
	devFixtureCommandLeaseLimit = 64
)

// devFixtureRunner is the sessionrepo command-runner surface the explicit
// development fixture route requires. It is satisfied by the reviewed
// sandbox-backed sessionlaunch.DevelopmentCommandRunner and by the bounded
// fallback below.
type devFixtureRunner interface {
	sessionrepo.CommandRunner
	sessionrepo.CommandRunnerProfile
	RegisterLease(viewID, leaseID string) error
	VerifySettlement(settlement sessionrepo.CommandSettlement, viewID, leaseID string) error
}

// newDevelopmentFixtureCommandRunner prefers the reviewed sandbox-backed
// command runner and falls back to the bounded, non-contained runner only when
// the development sandbox cannot be established on this host (for example, no
// Landlock ABI or missing namespaces). The chosen runner's Profile() is recorded
// in durable evidence and rechecked in the receipt, so the route never hides
// which runner actually ran. It never claims production containment.
func newDevelopmentFixtureCommandRunner() devFixtureRunner {
	if runner, err := sessionlaunch.NewDevelopmentCommandRunner(sandbox.Limits{}); err == nil {
		return runner
	}
	return newBoundedDevelopmentFixtureCommandRunner()
}

// devFixtureCommandRunner is the explicit BOUNDED, NON-CONTAINED fallback
// command runner for the offline `serve --pi --dev-fixture` route when the
// reviewed sandbox runner cannot run. It runs the authorized
// `/bin/bash -lc <command>` directly, under the current process's own
// credentials and namespaces, with its working directory pinned to the private
// mode-0700 session-repository command view and a fixed minimal environment. It:
//
//   - bounds wall-clock time (devFixtureCommandTimeout) and captured output
//     (devFixtureCommandOutputMax);
//   - starts the command in its own process group and proves the group empty
//     before reporting the scope settled;
//   - makes NO containment, network-isolation, filesystem-isolation, or
//     mount-detachment claim: the command can reach the network, the host
//     filesystem outside the view, and any ambient authority of the supervisor.
//
// It exists only so the real durable Bash lease path can be exercised offline.
// It is development-only (Linux-tagged) and is never reachable from production
// `serve --pi`; production must use a reviewed containment profile.
type devFixtureCommandRunner struct {
	mu       sync.Mutex
	leases   map[string]string
	receipts map[string]sessionrepo.CommandSettlement
}

func newBoundedDevelopmentFixtureCommandRunner() *devFixtureCommandRunner {
	return &devFixtureCommandRunner{
		leases:   make(map[string]string),
		receipts: make(map[string]sessionrepo.CommandSettlement),
	}
}

// Profile is the descriptive, non-claim-bearing evidence label recorded by the
// session repository. It is not a containment proof.
func (r *devFixtureCommandRunner) Profile() string {
	if r == nil {
		return "dev-fixture-bounded-non-claim-bearing:unavailable"
	}
	return devFixtureCommandProfile
}

// RegisterLease is called only from the concrete development authority after
// it has matched an ALLOW proposal to the exact current generation. The view ID
// is generated by sessionrepo before the runner receives the view; a model or
// caller cannot set it.
func (r *devFixtureCommandRunner) RegisterLease(viewID, leaseID string) error {
	if r == nil || strings.TrimSpace(viewID) == "" || strings.TrimSpace(leaseID) == "" {
		return errors.New("development fixture command runner requires a view and lease identity")
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if _, exists := r.leases[viewID]; exists || len(r.leases) >= devFixtureCommandLeaseLimit {
		return errors.New("development fixture command lease budget exhausted or duplicated")
	}
	r.leases[viewID] = leaseID
	return nil
}

// Run executes the authorized command and returns a bounded result plus a
// measured, one-use settlement receipt. A non-zero exit is still a known
// command result; a missing lease, an unbounded/late command, or a process
// scope that does not settle is an error and the result is withheld.
func (r *devFixtureCommandRunner) Run(ctx context.Context, view *sessionrepo.CommandView, spec sessionrepo.CommandSpec) (sessionrepo.CommandResult, sessionrepo.CommandSettlement, error) {
	if r == nil || ctx == nil {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, errors.New("development fixture command runner requires a context")
	}
	if spec.Executable != "/bin/bash" || len(spec.Args) != 2 || spec.Args[0] != "-lc" || strings.TrimSpace(spec.Args[1]) == "" {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, errors.New("development fixture command runner accepts only the registered /bin/bash -lc command shape")
	}
	if view == nil {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, errors.New("development fixture command runner requires a command view")
	}
	viewID := view.ID()
	r.mu.Lock()
	leaseID, registered := r.leases[viewID]
	r.mu.Unlock()
	if !registered {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, errors.New("development fixture command runner has no authorized lease for this command view")
	}
	rootPath, err := devFixtureCommandViewPath(view)
	if err != nil {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, err
	}
	workingDir, err := devFixtureCommandWorkingDir(rootPath, spec.WorkingDirectory)
	if err != nil {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, err
	}

	runCtx, cancel := context.WithTimeout(ctx, devFixtureCommandTimeout)
	defer cancel()
	command := exec.CommandContext(runCtx, spec.Executable, spec.Args...)
	command.Dir = workingDir
	// A fixed minimal environment with no inherited credentials or host paths.
	command.Env = []string{
		"PATH=/usr/bin:/bin:/usr/sbin:/sbin",
		"HOME=" + rootPath, "TMPDIR=" + rootPath, "LANG=C", "PI_OFFLINE=1",
	}
	// Own process group so the whole command scope can be signalled and proven
	// empty after the direct child exits.
	command.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	stdout := &devFixtureBoundedBuffer{max: devFixtureCommandOutputMax}
	stderr := &devFixtureBoundedBuffer{max: devFixtureCommandOutputMax}
	command.Stdout = stdout
	command.Stderr = stderr
	runErr := command.Run()

	// A canceled/deadline context is a withheld result, never a command result.
	if runCtx.Err() != nil {
		if command.Process != nil {
			_ = syscall.Kill(-command.Process.Pid, syscall.SIGKILL)
		}
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, fmt.Errorf("development fixture bash exceeded its bounded time: %w", runCtx.Err())
	}
	if stdout.truncated || stderr.truncated {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, errors.New("development fixture bash output exceeded its bound; result withheld")
	}
	exitCode, observed, err := devFixtureCommandExitCode(command, runErr)
	if err != nil {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, err
	}
	scopeEmpty, err := devFixtureReapScope(command.Process.Pid)
	if err != nil {
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, err
	}
	result := sessionrepo.CommandResult{
		ExitCode: exitCode, ExitObserved: observed,
		Stdout: stdout.Bytes(), Stderr: stderr.Bytes(),
	}
	settlement := sessionrepo.CommandSettlement{
		LeaseID: leaseID, ViewID: viewID,
		ProcessScopeEmpty: scopeEmpty,
		// The command's process scope is empty, so no writer from this bounded
		// command remains. This is a measured postcondition, not containment.
		WritersStopped: scopeEmpty,
		// This runner creates no mount cell, so there is no mount to detach.
		MountDetached: true,
		ExitObserved:  observed, ExitCode: exitCode,
		EvidenceClass: devFixtureCommandProfile,
	}
	if !scopeEmpty {
		// Fail closed: report the unsettled receipt so sessionrepo withholds the
		// result and quarantines the repository rather than importing a live view.
		return sessionrepo.CommandResult{}, settlement, errors.New("development fixture bash process scope did not settle")
	}
	r.mu.Lock()
	if _, duplicate := r.receipts[viewID]; duplicate {
		r.mu.Unlock()
		return sessionrepo.CommandResult{}, sessionrepo.CommandSettlement{}, errors.New("development fixture command view was already settled")
	}
	r.receipts[viewID] = settlement
	r.mu.Unlock()
	return result, settlement, nil
}

// VerifySettlement consumes the runner's one-use receipt. The candidate the
// store passes is compared against the settlement this runner actually
// measured; a caller-constructed settlement does not establish trust.
func (r *devFixtureCommandRunner) VerifySettlement(candidate sessionrepo.CommandSettlement, viewID, leaseID string) error {
	if r == nil {
		return errors.New("development fixture command runner is unavailable")
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	actual, exists := r.receipts[viewID]
	if !exists || actual.LeaseID != leaseID || actual.ViewID != viewID || actual != candidate ||
		!actual.ExitObserved || !actual.ProcessScopeEmpty || !actual.WritersStopped || !actual.MountDetached ||
		actual.EvidenceClass != devFixtureCommandProfile {
		return errors.New("development fixture command settlement receipt mismatch")
	}
	delete(r.receipts, viewID)
	delete(r.leases, viewID)
	return nil
}

// devFixtureCommandViewPath resolves the private command-view directory path
// from the O_PATH descriptor sessionrepo issues to the trusted runner.
func devFixtureCommandViewPath(view *sessionrepo.CommandView) (string, error) {
	root, err := view.MountSource()
	if err != nil {
		return "", fmt.Errorf("open development command view: %w", err)
	}
	path, readErr := os.Readlink(fmt.Sprintf("/proc/self/fd/%d", root.Fd()))
	closeErr := root.Close()
	if readErr != nil {
		return "", fmt.Errorf("resolve development command view path: %w", readErr)
	}
	if closeErr != nil {
		return "", fmt.Errorf("release development command view descriptor: %w", closeErr)
	}
	if !filepath.IsAbs(path) || strings.ContainsRune(path, 0) {
		return "", errors.New("development command view resolved to an invalid path")
	}
	return path, nil
}

// devFixtureCommandWorkingDir pins the command working directory to the private
// view root, rejecting an absolute or escaping relative directory exactly as
// the reviewed sandbox request validator does.
func devFixtureCommandWorkingDir(rootPath, relative string) (string, error) {
	if relative == "" {
		return rootPath, nil
	}
	clean := filepath.Clean(relative)
	if filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", errors.New("development fixture command working directory escapes the private view")
	}
	return filepath.Join(rootPath, clean), nil
}

// devFixtureCommandExitCode extracts a bounded exit status. A non-zero exit is a
// known result; a start failure is an error.
func devFixtureCommandExitCode(command *exec.Cmd, runErr error) (int, bool, error) {
	if runErr == nil {
		return 0, true, nil
	}
	var exitErr *exec.ExitError
	if errors.As(runErr, &exitErr) {
		if status, ok := exitErr.Sys().(syscall.WaitStatus); ok {
			if status.Signaled() {
				return 128 + int(status.Signal()), true, nil
			}
			return status.ExitStatus(), true, nil
		}
		if code := exitErr.ExitCode(); code >= 0 {
			return code, true, nil
		}
	}
	return 0, false, fmt.Errorf("development fixture bash could not start: %w", runErr)
}

// devFixtureReapScope signals the command's process group and waits until the
// group is empty, returning false (fail closed) if it does not settle. The
// child was started with Setpgid, so its process group ID equals its PID.
func devFixtureReapScope(pid int) (bool, error) {
	if pid <= 0 {
		return false, errors.New("development fixture command has no process identity")
	}
	_ = syscall.Kill(-pid, syscall.SIGKILL)
	deadline := time.Now().Add(devFixtureCommandScopeGrace)
	for {
		err := syscall.Kill(-pid, 0)
		if errors.Is(err, syscall.ESRCH) {
			return true, nil
		}
		if err != nil && !errors.Is(err, syscall.EPERM) {
			return false, fmt.Errorf("probe development fixture command scope: %w", err)
		}
		if time.Now().After(deadline) {
			return false, nil
		}
		time.Sleep(5 * time.Millisecond)
	}
}

// devFixtureBoundedBuffer captures at most max bytes and records whether the
// stream was truncated so the caller can fail closed instead of releasing a
// partial result as if it were complete.
type devFixtureBoundedBuffer struct {
	max       int
	buffer    []byte
	truncated bool
}

func (b *devFixtureBoundedBuffer) Write(data []byte) (int, error) {
	if remaining := b.max - len(b.buffer); remaining > 0 {
		if len(data) > remaining {
			b.buffer = append(b.buffer, data[:remaining]...)
			b.truncated = true
		} else {
			b.buffer = append(b.buffer, data...)
		}
	} else if len(data) > 0 {
		b.truncated = true
	}
	return len(data), nil
}

func (b *devFixtureBoundedBuffer) Bytes() []byte {
	return append([]byte(nil), b.buffer...)
}

// developmentFixtureAuthority is the non-claim-bearing authority for the
// explicit development fixture store. Read/edit/write decisions are accepted as
// the development seam already did; a Bash lease is registered with the selected
// development runner so the runner can return a measured settlement and the
// store can verify it. It supplies no D06/source/containment proof.
type developmentFixtureAuthority struct {
	commands devFixtureRunner
}

func (a developmentFixtureAuthority) authorize(request sessionrepo.OperationRequest) error {
	if request.Tool == "bash" {
		if a.commands == nil {
			return errors.New("development fixture has no command runner for a bash lease")
		}
		return a.commands.RegisterLease(request.ViewID, request.Operation.LeaseID)
	}
	return nil
}

func (developmentFixtureAuthority) verifyDecision(delta.PolicyDecision, delta.TransitionBinding) error {
	return nil
}

func (a developmentFixtureAuthority) verifySettlement(settlement sessionrepo.CommandSettlement, viewID, leaseID string) error {
	if a.commands == nil {
		return errors.New("development fixture has no command runner to verify a bash settlement")
	}
	return a.commands.VerifySettlement(settlement, viewID, leaseID)
}
